name: "Build in a Nix shell"

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  build:
    name: "Build in a Nix shell"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop
      - run: dotnet build -c Debug
